version: "3.4"
services:
  cox-appointment-scheduler:
    container_name: cox-appointment-scheduler
    build:
      context: .
      dockerfile: Dockerfile-prod
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production
    