version: "2"
services:
  cox-appointment-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    image: gcr.io/autoscheduler-195814/cox-autoscheduler:1.0
    ports:
    - 80:3000  
    environment:
      NODE_ENV: development
      PORT: "3000"
     